version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler -v 2.1.4
      - run: bundle install
  test:
    docker: 
      - image: circleci/ruby:2.7.1-node
    steps:
      - checkout
      - run: bundle exec rspec

workflows:
  build_and_test: 
    jobs: 
      - build
      - test: 
          requires: 
            - build

