version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node
    executor: ruby/default
    steps:
      - checkout
      - restore_cache: 
          key: v3-env
      - run: gem install bundler -v 2.1.4
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache: 
          key: v3-env
          paths: 
            - vendor/bundle
  test:
    parallelism: 3
    docker: 
      - image: circleci/ruby:2.7.1-node
      - image: circleci/postgres:11.0-alpine
        environment: 
          POSTGRES_USER: book_worm_be
          POSTGRES_DB: book_worm_be_production
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: book_worm_be
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: v3-env
      - run: gem install bundler -v 2.1.4
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: bundle exec rails db:{create,migrate} RAILS_ENV=test
      - run: bundle exec rspec
      - save_cache:
          key: v3-env
          paths: vendor/bundle
  deploy: 
    executor: heroku/default
    steps: 
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  build_and_test_and_deploy: 
    jobs: 
      - build
      - test: 
          requires: 
            - build
      - deploy:
          requires:
            - build
            - test
          filters: 
            branches:
              only: main
